<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="Anshuls-MacBook-M3.local" failures="1" tests="5" name="Listener Test Case" time="0.031" errors="0" timestamp="2024-01-19T22:17:17 IST">
  <testcase classname="com.testng.listeners.SampleTestClass" name="testFour" time="0.004">
    <skipped/>
  </testcase> <!-- testFour -->
  <testcase classname="com.testng.listeners.SampleTestClass" name="testGetData" time="0.001"/>
  <testcase classname="com.testng.listeners.SampleTestClass" name="testGetData" time="0.0"/>
  <testcase classname="com.testng.listeners.SampleTestClass" name="testOne" time="0.001"/>
  <testcase classname="com.testng.listeners.SampleTestClass" name="testThree" time="0.003">
    <failure type="java.lang.AssertionError" message="expected [7] but found [5]">
      <![CDATA[java.lang.AssertionError: expected [7] but found [5]
at com.testng.listeners.SampleTestClass.testThree(SampleTestClass.java:26)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
... Removed 32 stack frames]]>
    </failure>
  </testcase> <!-- testThree -->
</testsuite> <!-- Listener Test Case -->
